# Generated by Django 5.1.1 on 2024-09-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForjaApp', '0002_remove_movie_actors_remove_movie_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster_path',
            field=models.ImageField(upload_to='posters/'),
        ),
    ]
